### ISSUE TITLE
Asking about detailed algorithm

### ISSUE THREAD

**Issue by vhchuong** [Kashi7/Finger-Count-Using-OpenCV#1]
Dear @Kashi7 , 
I tried your code and found it really interesting and efficient.
Do you have the detailed algorithm explanation for this code?
Thank you very much!
I hope to hear from you soon!

**Comment by Kashi7** [comment]
Yes will forward it by tomorrow.

**Comment by Kashi7** [comment]
[Finger Count.docx](https://github.com/Kashi7/Finger-Count-Using-OpenCV/files/4567186/Finger.Count.docx)
